export const  TEXT = {
    isCustomer: 'Là khách hàng',
    isSuplier: 'Là nhà cung cấp',
    employee: "Nhân viên",
    addEmployee: "Thêm mới nhân viên",
    save: "Cất",
    cancel: "Hủy",
    cancelSecond: "Hủy bỏ",
    saveAndContinue: "Cất và Thêm",
    confirm: "Có",
    confirmDeleteEmployee:"Có, xóa nhân viên",
    deny: "Không",
    delete: "Xóa",
    selected: "Đã chọn",
    removeSelected: "Bỏ chọn",
    edit: "Sửa",
    nonData: "Không có dữ liệu",
    male: "Nam",
    feMale: "Nữ",
    other: "Khác",
    titleDeleteEmp: "Xóa nhân viên",
    titleEditEmp: "Sửa nhân viên",
    titleAddEmp: "Thêm mới nhân viên",
    recordPerPage: "bản ghi trên trang",
    refeshData: "Làm mới dữ liệu",
    deleteBatchConfirm: "Các bản ghi bạn đang chọn sẽ bị xóa.",
    titleBrowser: "Amis-Quản lý nhân sự",
    descriptionDialogChangeData: [
        {
          name: "Thông báo",
          value: "Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",
        },
    ],
    total: "Tổng",
}

export const FIELD_NAME = {
    employeeCode: "Mã nhân viên",
    employeeName: "Tên nhân viên",
    gender: "Giới tính",
    departmentName: "Tên Đơn vị",
    departmentCode: "Mã Đơn vị",
    position: "Chức danh",
    identityNumber: "Số CMND",
    indentityDate: "Ngày cấp",
    indentityPlace: "Nơi cấp",
    dateOfBirth: "Ngày sinh",
    bankNumber: "Tài khoản ngân hàng",
    bankName: "Tên ngân hàng",
    branchName: "Chi nhánh",
    email: "Email",
    phoneNumber: "ĐT cố định",
    telePhoneNumber: "ĐT di động",
    address: "Địa chỉ",    
}

export const TOOLTIP = {
    exportExcel: "Xuất Khẩu",
    identityNumber: "Số chứng minh nhân dân",
    telephoneNumber: "Điện thoại di động",
    phoneNumber: "Điện thoại cố định",
    bankBranch: "Chi nhánh tài khoản ngân hàng",
    close: "Đóng",
    info:"Thông tin",
}

export const NAME_DISPLAY = {
    employeeCode: "Mã nhân viên",
    employeeName: "Tên nhân viên",
    department: "Đơn vị",
    positionName: "Chức vụ",
    identitynumber : "Số chứng minh nhân dân",
    dateOfBirth: "Ngày sinh",
    bankNumber: "Số tài khoản",
    bankName: "Tên ngân hàng",
    branchName: "Chi nhánh",
    email: "Email",
    telephoneNumber: "Số điện thoại",
    phoneNumber: "Số điện thoại cố định",
}

export const PLACEHOLDER = {
    searchCodeAndName: "Tìm theo mã, tên nhân viên",
    employeeCode: "NV001",
    employeeName: "Nguyễn Văn A",
    jobPositionName: "Trưởng phòng kinh doanh",
    identityNumber: "123456789",
    identityPlace:"Hà Nội",
    address: "Số 1, đường 1, phường 1, quận 1, thành phố 1",
    telephoneNumber: "0123456789",
    phoneNumber: "0123456789",
    email: "company@example.com",
    bankNumber: "123456789101112",
    bankName: "Ngân hàng A",
    branchName: "Chi nhánh A",
}